Repository FlowFans/flow-token-list, pull requests merged in 2022-04, with the labels that each got.

#8 feat: add ftl-pr-checker workflow
  .github/workflows/ftl-pr-checker.yml
Labels: UnrelatedToToken

#12 feat(UpdateToken): update ceMATIC logo
  token-registry/ceMATIC/logo.png
Labels: UpdateToken

#13 feat(UpdateToken): update USDC logos
  token-registry/USDC/logo-large.png
  token-registry/USDC/logo.png
  token-registry/USDC/testnet.token.json
Labels: UpdateToken

#10 feat: add npm lib
  .prettierignore
  README.md
  package.json
  src/index.ts
  src/lib/tokenlist.spec.ts
  src/lib/tokenlist.ts
  yarn.lock
Labels: UnrelatedToToken

#11 feat(NewToken): add REVV
  token-registry/REVV/logo.png
  token-registry/REVV/token.json
Labels: NewToken

#15 feat: update generator to support versioning
  src/tokens/flow-mainnet.tokenlist.json
  src/tokens/flow-testnet.tokenlist.json
  src/utils/tokenlist-generator.js
Labels: UnrelatedToToken

#17 feat: update README
  README.md
Labels: UnrelatedToToken

#18 docs: update README
  README.md
Labels: UnrelatedToToken

#19 Update doc with npm example
  README.md
Labels: UnrelatedToToken

#21 feat(UpdateToken): wbtc logo
  token-registry/A.0x231cc0dbbcffc4b7.ceWBTC/logo.png
Labels: UpdateToken

#23 feat: update celer tokens
  src/tokens/flow-mainnet.tokenlist.json
  token-registry/A.0x231cc0dbbcffc4b7.ceAVAX/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceBNB/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceBUSD/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceDAI/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceFTM/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceMATIC/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceUSDT/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceWBTC/token.json
  token-registry/A.0x231cc0dbbcffc4b7.ceWETH/token.json
Labels: UpdateToken

#25 feat(NewToken): add RLY
  token-registry/A.0x231cc0dbbcffc4b7.RLY/logo.png
  token-registry/A.0x231cc0dbbcffc4b7.RLY/token.json
Labels: NewToken

#29 feat(UpdateToken): add teleported-token tag to USDT
  token-registry/A.cfdd90d4a00f7b5b.TeleportedTetherToken/token.json
Labels: UpdateToken

#28 feat(NewToken): add SPRT
  token-registry/A.475755d2c9dccc3a.TeleportedSportiumToken/logo.png
  token-registry/A.475755d2c9dccc3a.TeleportedSportiumToken/token.json
Labels: NewToken
